version: '2'
services:

  elasticsearch:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    environment:
      - MAX_MAP_COUNT=262144
  logstash:
    build: logstash
    ports:
      - "9600:9600"
    volumes:
      - log_pipeline:/usr/share/logstash/pipeline
      - log_app:/app
      - log_logs:/usr/share/logstash/logs

volumes:
  log_pipeline:
  log_app:
  log_logs: